# Generated by Django 5.2.7 on 2025-10-16 00:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_sessions_per_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_rate_per_minute', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_type', models.CharField(choices=[('reps', 'Repetitions'), ('km', 'Kilometers')], default='reps', max_length=10)),
                ('category', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('flexibility', 'Flexibility')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('role', models.IntegerField(choices=[(0, 'User'), (1, 'Admin')], default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('challenge_type', models.IntegerField(choices=[(0, 'Habit'), (1, 'Target')])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('threshold_percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('active_participant_count', models.PositiveIntegerField(default=0)),
                ('trending_score', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('failed_count', models.PositiveSmallIntegerField(default=0)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'ip'], name='myapp_login_email_440311_idx')],
                'constraints': [models.UniqueConstraint(fields=('email', 'ip'), name='unique_email_ip_loginthrottle')],
            },
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='myapp.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitChallenge',
            fields=[
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='habit_details', serialize=False, to='myapp.challenge')),
                ('duration_weeks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('frequency_per_week', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habit_challenges', to='myapp.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='TargetChallenge',
            fields=[
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='target_details', serialize=False, to='myapp.challenge')),
                ('duration_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('target_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_challenges', to='myapp.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.IntegerField(choices=[(0, 'Participant'), (1, 'Owner')], default=0)),
                ('state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('left', 'Left')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='myapp.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('challenge', 'user'), name='unique_participant_per_challenge')],
            },
        ),
    ]
