# Generated by Django 5.1.13 on 2025-10-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_add_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default='blank_profile_pic.jpg', null=True, upload_to='avatars/'),
        ),
    ]
