# Generated by Django 5.1.13 on 2025-10-25 10:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressentry',
            name='duration_minutes',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))]),
            preserve_default=False,
        ),
    ]
