# Generated by Django 5.1.13 on 2025-10-25 08:59

from django.db import migrations
from myapp.models import User


def create_admin_user(apps, schema_editor):
    """Create the default admin user if it doesn't exist."""
    admin_email = 'admin@admin.com'
    admin_password = 'Trueadmin123'
    admin_display_name = 'Admin User'

    # Check if admin user already exists
    if not User.objects.filter(email=admin_email).exists():
        admin_user = User.objects.create_superuser(
            email=admin_email,
            password=admin_password,
            display_name=admin_display_name
        )
        # Set the custom role to Admin
        admin_user.role = 1  # Admin role
        admin_user.save()


def reverse_create_admin_user(apps, schema_editor):
    """Remove the admin user (optional - you might not want this)."""
    admin_email = 'admin@admin.com'
    User.objects.filter(email=admin_email).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_progressentry_duration_minutes'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_create_admin_user),
    ]
